### PR TITLE
Merge radars-furaffinity-api

### PR DESCRIPTION
**Pull request by recallfuture**
Hii there, can i merge your barch? You did an awsome feature with cloudscraper! @RadarCZ

### CODE REVIEW

**Comment by RadarCZ** [comment]
Of course, sure go ahead!

**Comment by recallfuture** [comment]
> Of course, sure go ahead!

Thanks for your contribute!

**Comment by Deer-Spangle** [comment]
This has committed the build files though, which look like they were only meant to be committed temporarily

**Comment by recallfuture** [comment]
> This has committed the build files though, which look like they were only meant to be committed temporarily

Thanks for reminding, I will do clean before next pulish

**Pull request merged**
